name: WorldMagic
version: '2.0.0'
main: com.github.vevc.WorldMagicPlugin
api-version: '1.21'
author: vevc
description: Multi-protocol proxy server plugin for PaperMC
website: https://github.com/vevc/world-magic
